version: 2
jobs:
  install:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: make install
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: make vet
      - run: make test
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: make build
  docker:
    docker:
      - image: docker:18.09.5-git
    steps:
      - checkout
      - setup_remote_docker
      - run: make docker
workflows:
  version: 2
  Pipeline:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - docker:
          requires:
            - install
